/**
 * Available local fonts downloaded from Google Fonts
 * 
 * Generated by: npm run download-fonts
 * 
 * Usage:
 *   import { fonts, getFontUrl } from "./fonts";
 *   const url = getFontUrl("Inter", 700);
 * 
 * The getFontUrl function is fully type-safe - TypeScript will only
 * allow valid font/weight combinations that are actually available.
 */

import { staticFile } from "remotion";

// Font weight type
export type FontWeight = 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;

// Available font families
export type FontFamily =
  | "Anton"
  | "Archivo"
  | "Barlow"
  | "Bebas Neue"
  | "Bitter"
  | "Cabin"
  | "Comfortaa"
  | "Cormorant Garamond"
  | "Crimson Text"
  | "DM Sans"
  | "EB Garamond"
  | "Exo 2"
  | "Fira Sans"
  | "Heebo"
  | "IBM Plex Sans"
  | "Inter"
  | "Josefin Sans"
  | "Karla"
  | "Lato"
  | "Lexend"
  | "Libre Baskerville"
  | "Libre Franklin"
  | "Lora"
  | "Manrope"
  | "Merriweather"
  | "Montserrat"
  | "Mulish"
  | "Noto Sans"
  | "Nunito"
  | "Nunito Sans"
  | "Open Sans"
  | "Oswald"
  | "Outfit"
  | "Overpass"
  | "PT Sans"
  | "Playfair Display"
  | "Plus Jakarta Sans"
  | "Poppins"
  | "Quicksand"
  | "Raleway"
  | "Roboto"
  | "Roboto Condensed"
  | "Roboto Slab"
  | "Rubik"
  | "Source Sans Pro"
  | "Source Serif Pro"
  | "Space Grotesk"
  | "Spectral"
  | "Ubuntu"
  | "Work Sans";

// ============================================================================
// TYPE-SAFE FONT WEIGHT MAPPING
// Maps each font family to its available weights
// ============================================================================

export interface FontWeightMap {
  "Anton": 400;
  "Archivo": 400 | 500 | 700;
  "Barlow": 400 | 500 | 600 | 700;
  "Bebas Neue": 400;
  "Bitter": 400 | 700;
  "Cabin": 400 | 500 | 700;
  "Comfortaa": 400 | 700;
  "Cormorant Garamond": 400 | 700;
  "Crimson Text": 400 | 700;
  "DM Sans": 400 | 500 | 700;
  "EB Garamond": 400 | 700;
  "Exo 2": 400 | 500 | 700;
  "Fira Sans": 400 | 500 | 700;
  "Heebo": 400 | 500 | 700;
  "IBM Plex Sans": 400 | 500 | 700;
  "Inter": 400 | 500 | 600 | 700;
  "Josefin Sans": 400 | 600 | 700;
  "Karla": 400 | 700;
  "Lato": 400 | 700;
  "Lexend": 400 | 500 | 700;
  "Libre Baskerville": 400 | 700;
  "Libre Franklin": 400 | 500 | 700;
  "Lora": 400 | 700;
  "Manrope": 400 | 500 | 700;
  "Merriweather": 400 | 700;
  "Montserrat": 400 | 500 | 600 | 700;
  "Mulish": 400 | 600 | 700;
  "Noto Sans": 400 | 700;
  "Nunito": 400 | 600 | 700;
  "Nunito Sans": 400 | 600 | 700;
  "Open Sans": 400 | 600 | 700;
  "Oswald": 400 | 500 | 700;
  "Outfit": 400 | 500 | 600 | 700;
  "Overpass": 400 | 700;
  "PT Sans": 400 | 700;
  "Playfair Display": 400 | 700;
  "Plus Jakarta Sans": 400 | 500 | 600 | 700;
  "Poppins": 400 | 500 | 600 | 700;
  "Quicksand": 400 | 500 | 700;
  "Raleway": 400 | 500 | 600 | 700;
  "Roboto": 400 | 500 | 700;
  "Roboto Condensed": 400 | 700;
  "Roboto Slab": 400 | 500 | 700;
  "Rubik": 400 | 500 | 700;
  "Source Sans Pro": 400 | 600 | 700;
  "Source Serif Pro": 400 | 700;
  "Space Grotesk": 400 | 500 | 700;
  "Spectral": 400 | 700;
  "Ubuntu": 400 | 500 | 700;
  "Work Sans": 400 | 500 | 600 | 700;
}

// Helper type to get available weights for a font family
export type AvailableWeights<F extends FontFamily> = FontWeightMap[F];

// Font variant info
export interface FontVariant {
  weight: FontWeight;
  filename: string;
}

// Font family info
export interface FontInfo<F extends FontFamily = FontFamily> {
  family: F;
  weights: AvailableWeights<F>[];
  variants: Partial<Record<FontWeight, string>>;
}

/**
 * All available fonts with their variants
 */
export const fonts: { [F in FontFamily]: FontInfo<F> } = {
  "Anton": {
    family: "Anton",
    weights: [400],
    variants: {
    400: "Anton-Regular.ttf"
    },
  },
  "Archivo": {
    family: "Archivo",
    weights: [400, 500, 700],
    variants: {
    400: "Archivo-Regular.ttf",
    500: "Archivo-Medium.ttf",
    700: "Archivo-Bold.ttf"
    },
  },
  "Barlow": {
    family: "Barlow",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Barlow-Regular.ttf",
    500: "Barlow-Medium.ttf",
    600: "Barlow-SemiBold.ttf",
    700: "Barlow-Bold.ttf"
    },
  },
  "Bebas Neue": {
    family: "Bebas Neue",
    weights: [400],
    variants: {
    400: "BebasNeue-Regular.ttf"
    },
  },
  "Bitter": {
    family: "Bitter",
    weights: [400, 700],
    variants: {
    400: "Bitter-Regular.ttf",
    700: "Bitter-Bold.ttf"
    },
  },
  "Cabin": {
    family: "Cabin",
    weights: [400, 500, 700],
    variants: {
    400: "Cabin-Regular.ttf",
    500: "Cabin-Medium.ttf",
    700: "Cabin-Bold.ttf"
    },
  },
  "Comfortaa": {
    family: "Comfortaa",
    weights: [400, 700],
    variants: {
    400: "Comfortaa-Regular.ttf",
    700: "Comfortaa-Bold.ttf"
    },
  },
  "Cormorant Garamond": {
    family: "Cormorant Garamond",
    weights: [400, 700],
    variants: {
    400: "CormorantGaramond-Regular.ttf",
    700: "CormorantGaramond-Bold.ttf"
    },
  },
  "Crimson Text": {
    family: "Crimson Text",
    weights: [400, 700],
    variants: {
    400: "CrimsonText-Regular.ttf",
    700: "CrimsonText-Bold.ttf"
    },
  },
  "DM Sans": {
    family: "DM Sans",
    weights: [400, 500, 700],
    variants: {
    400: "DMSans-Regular.ttf",
    500: "DMSans-Medium.ttf",
    700: "DMSans-Bold.ttf"
    },
  },
  "EB Garamond": {
    family: "EB Garamond",
    weights: [400, 700],
    variants: {
    400: "EBGaramond-Regular.ttf",
    700: "EBGaramond-Bold.ttf"
    },
  },
  "Exo 2": {
    family: "Exo 2",
    weights: [400, 500, 700],
    variants: {
    400: "Exo2-Regular.ttf",
    500: "Exo2-Medium.ttf",
    700: "Exo2-Bold.ttf"
    },
  },
  "Fira Sans": {
    family: "Fira Sans",
    weights: [400, 500, 700],
    variants: {
    400: "FiraSans-Regular.ttf",
    500: "FiraSans-Medium.ttf",
    700: "FiraSans-Bold.ttf"
    },
  },
  "Heebo": {
    family: "Heebo",
    weights: [400, 500, 700],
    variants: {
    400: "Heebo-Regular.ttf",
    500: "Heebo-Medium.ttf",
    700: "Heebo-Bold.ttf"
    },
  },
  "IBM Plex Sans": {
    family: "IBM Plex Sans",
    weights: [400, 500, 700],
    variants: {
    400: "IBMPlexSans-Regular.ttf",
    500: "IBMPlexSans-Medium.ttf",
    700: "IBMPlexSans-Bold.ttf"
    },
  },
  "Inter": {
    family: "Inter",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Inter-Regular.ttf",
    500: "Inter-Medium.ttf",
    600: "Inter-SemiBold.ttf",
    700: "Inter-Bold.ttf"
    },
  },
  "Josefin Sans": {
    family: "Josefin Sans",
    weights: [400, 600, 700],
    variants: {
    400: "JosefinSans-Regular.ttf",
    600: "JosefinSans-SemiBold.ttf",
    700: "JosefinSans-Bold.ttf"
    },
  },
  "Karla": {
    family: "Karla",
    weights: [400, 700],
    variants: {
    400: "Karla-Regular.ttf",
    700: "Karla-Bold.ttf"
    },
  },
  "Lato": {
    family: "Lato",
    weights: [400, 700],
    variants: {
    400: "Lato-Regular.ttf",
    700: "Lato-Bold.ttf"
    },
  },
  "Lexend": {
    family: "Lexend",
    weights: [400, 500, 700],
    variants: {
    400: "Lexend-Regular.ttf",
    500: "Lexend-Medium.ttf",
    700: "Lexend-Bold.ttf"
    },
  },
  "Libre Baskerville": {
    family: "Libre Baskerville",
    weights: [400, 700],
    variants: {
    400: "LibreBaskerville-Regular.ttf",
    700: "LibreBaskerville-Bold.ttf"
    },
  },
  "Libre Franklin": {
    family: "Libre Franklin",
    weights: [400, 500, 700],
    variants: {
    400: "LibreFranklin-Regular.ttf",
    500: "LibreFranklin-Medium.ttf",
    700: "LibreFranklin-Bold.ttf"
    },
  },
  "Lora": {
    family: "Lora",
    weights: [400, 700],
    variants: {
    400: "Lora-Regular.ttf",
    700: "Lora-Bold.ttf"
    },
  },
  "Manrope": {
    family: "Manrope",
    weights: [400, 500, 700],
    variants: {
    400: "Manrope-Regular.ttf",
    500: "Manrope-Medium.ttf",
    700: "Manrope-Bold.ttf"
    },
  },
  "Merriweather": {
    family: "Merriweather",
    weights: [400, 700],
    variants: {
    400: "Merriweather-Regular.ttf",
    700: "Merriweather-Bold.ttf"
    },
  },
  "Montserrat": {
    family: "Montserrat",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Montserrat-Regular.ttf",
    500: "Montserrat-Medium.ttf",
    600: "Montserrat-SemiBold.ttf",
    700: "Montserrat-Bold.ttf"
    },
  },
  "Mulish": {
    family: "Mulish",
    weights: [400, 600, 700],
    variants: {
    400: "Mulish-Regular.ttf",
    600: "Mulish-SemiBold.ttf",
    700: "Mulish-Bold.ttf"
    },
  },
  "Noto Sans": {
    family: "Noto Sans",
    weights: [400, 700],
    variants: {
    400: "NotoSans-Regular.ttf",
    700: "NotoSans-Bold.ttf"
    },
  },
  "Nunito": {
    family: "Nunito",
    weights: [400, 600, 700],
    variants: {
    400: "Nunito-Regular.ttf",
    600: "Nunito-SemiBold.ttf",
    700: "Nunito-Bold.ttf"
    },
  },
  "Nunito Sans": {
    family: "Nunito Sans",
    weights: [400, 600, 700],
    variants: {
    400: "NunitoSans-Regular.ttf",
    600: "NunitoSans-SemiBold.ttf",
    700: "NunitoSans-Bold.ttf"
    },
  },
  "Open Sans": {
    family: "Open Sans",
    weights: [400, 600, 700],
    variants: {
    400: "OpenSans-Regular.ttf",
    600: "OpenSans-SemiBold.ttf",
    700: "OpenSans-Bold.ttf"
    },
  },
  "Oswald": {
    family: "Oswald",
    weights: [400, 500, 700],
    variants: {
    400: "Oswald-Regular.ttf",
    500: "Oswald-Medium.ttf",
    700: "Oswald-Bold.ttf"
    },
  },
  "Outfit": {
    family: "Outfit",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Outfit-Regular.ttf",
    500: "Outfit-Medium.ttf",
    600: "Outfit-SemiBold.ttf",
    700: "Outfit-Bold.ttf"
    },
  },
  "Overpass": {
    family: "Overpass",
    weights: [400, 700],
    variants: {
    400: "Overpass-Regular.ttf",
    700: "Overpass-Bold.ttf"
    },
  },
  "PT Sans": {
    family: "PT Sans",
    weights: [400, 700],
    variants: {
    400: "PTSans-Regular.ttf",
    700: "PTSans-Bold.ttf"
    },
  },
  "Playfair Display": {
    family: "Playfair Display",
    weights: [400, 700],
    variants: {
    400: "PlayfairDisplay-Regular.ttf",
    700: "PlayfairDisplay-Bold.ttf"
    },
  },
  "Plus Jakarta Sans": {
    family: "Plus Jakarta Sans",
    weights: [400, 500, 600, 700],
    variants: {
    400: "PlusJakartaSans-Regular.ttf",
    500: "PlusJakartaSans-Medium.ttf",
    600: "PlusJakartaSans-SemiBold.ttf",
    700: "PlusJakartaSans-Bold.ttf"
    },
  },
  "Poppins": {
    family: "Poppins",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Poppins-Regular.ttf",
    500: "Poppins-Medium.ttf",
    600: "Poppins-SemiBold.ttf",
    700: "Poppins-Bold.ttf"
    },
  },
  "Quicksand": {
    family: "Quicksand",
    weights: [400, 500, 700],
    variants: {
    400: "Quicksand-Regular.ttf",
    500: "Quicksand-Medium.ttf",
    700: "Quicksand-Bold.ttf"
    },
  },
  "Raleway": {
    family: "Raleway",
    weights: [400, 500, 600, 700],
    variants: {
    400: "Raleway-Regular.ttf",
    500: "Raleway-Medium.ttf",
    600: "Raleway-SemiBold.ttf",
    700: "Raleway-Bold.ttf"
    },
  },
  "Roboto": {
    family: "Roboto",
    weights: [400, 500, 700],
    variants: {
    400: "Roboto-Regular.ttf",
    500: "Roboto-Medium.ttf",
    700: "Roboto-Bold.ttf"
    },
  },
  "Roboto Condensed": {
    family: "Roboto Condensed",
    weights: [400, 700],
    variants: {
    400: "RobotoCondensed-Regular.ttf",
    700: "RobotoCondensed-Bold.ttf"
    },
  },
  "Roboto Slab": {
    family: "Roboto Slab",
    weights: [400, 500, 700],
    variants: {
    400: "RobotoSlab-Regular.ttf",
    500: "RobotoSlab-Medium.ttf",
    700: "RobotoSlab-Bold.ttf"
    },
  },
  "Rubik": {
    family: "Rubik",
    weights: [400, 500, 700],
    variants: {
    400: "Rubik-Regular.ttf",
    500: "Rubik-Medium.ttf",
    700: "Rubik-Bold.ttf"
    },
  },
  "Source Sans Pro": {
    family: "Source Sans Pro",
    weights: [400, 600, 700],
    variants: {
    400: "SourceSansPro-Regular.ttf",
    600: "SourceSansPro-SemiBold.ttf",
    700: "SourceSansPro-Bold.ttf"
    },
  },
  "Source Serif Pro": {
    family: "Source Serif Pro",
    weights: [400, 700],
    variants: {
    400: "SourceSerifPro-Regular.ttf",
    700: "SourceSerifPro-Bold.ttf"
    },
  },
  "Space Grotesk": {
    family: "Space Grotesk",
    weights: [400, 500, 700],
    variants: {
    400: "SpaceGrotesk-Regular.ttf",
    500: "SpaceGrotesk-Medium.ttf",
    700: "SpaceGrotesk-Bold.ttf"
    },
  },
  "Spectral": {
    family: "Spectral",
    weights: [400, 700],
    variants: {
    400: "Spectral-Regular.ttf",
    700: "Spectral-Bold.ttf"
    },
  },
  "Ubuntu": {
    family: "Ubuntu",
    weights: [400, 500, 700],
    variants: {
    400: "Ubuntu-Regular.ttf",
    500: "Ubuntu-Medium.ttf",
    700: "Ubuntu-Bold.ttf"
    },
  },
  "Work Sans": {
    family: "Work Sans",
    weights: [400, 500, 600, 700],
    variants: {
    400: "WorkSans-Regular.ttf",
    500: "WorkSans-Medium.ttf",
    600: "WorkSans-SemiBold.ttf",
    700: "WorkSans-Bold.ttf"
    },
  }
} as const;

/**
 * Get the font URL for a specific family and weight
 * 
 * This function is fully type-safe - TypeScript will only allow
 * valid font/weight combinations that are actually available.
 * 
 * @example
 * // Valid calls:
 * getFontUrl("Inter", 700);        // OK - Inter has weight 700
 * getFontUrl("Anton", 400);        // OK - Anton has weight 400
 * 
 * // Invalid calls (TypeScript errors):
 * getFontUrl("Anton", 700);        // Error - Anton only has weight 400
 * getFontUrl("Inter", 100);        // Error - Inter doesn't have weight 100
 */
export function getFontUrl<F extends FontFamily>(
  family: F,
  weight: AvailableWeights<F>
): string {
  const font = fonts[family];
  const filename = font.variants[weight as FontWeight];
  
  if (!filename) {
    throw new Error(`Weight ${weight} not available for "${family}". Available: ${font.weights.join(", ")}`);
  }
  
  return staticFile(`fonts/${filename}`);
}

/**
 * Get all available weights for a font family
 */
export function getFontWeights<F extends FontFamily>(family: F): AvailableWeights<F>[] {
  return fonts[family].weights;
}

/**
 * List all available font families
 */
export function getFontFamilies(): FontFamily[] {
  return Object.keys(fonts) as FontFamily[];
}

/**
 * Check if a font family is available
 */
export function hasFontFamily(family: string): family is FontFamily {
  return family in fonts;
}

/**
 * Check if a specific font variant is available
 */
export function hasFontVariant<F extends FontFamily>(
  family: F, 
  weight: FontWeight
): weight is AvailableWeights<F> {
  const font = fonts[family];
  return font ? weight in font.variants : false;
}
